name: ci-lint
on:
  push:
    branches:
      - "main"

jobs:
  ci-lint-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Bash
        run: |
          sudo apt-get update
          sudo apt-get install -y bash
      - name: Run lint.sh
        run:
          $GITHUB_WORKSPACE/backend/ci/lint.sh

