name: ci-lint
on:
  push:
    branches:
      - "main"

jobs:
  ci-lint-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Bash
        run: |
          sudo apt-get update
          sudo apt-get install -y bash
      - run: cd backend/ci
      - name: Run lint.sh
        run:
          ./lint.sh

